obj-$(CONFIG_AST2500_ESPI)              += ast2500-espi.o
obj-$(CONFIG_AST2600_ESPI)              += ast2600-espi.o
obj-$(CONFIG_AST2700_ESPI)              += ast2700-espi.o
obj-$(CONFIG_AST2700_RTC_OVER_ESPI)     += ast2700-rtc-over-espi.o
